
services:
  db:
    image: mysql:8
    container_name: demo_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: demo_login
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: demo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  db_data:
